name: end-to-end-tests

on:  
  workflow_dispatch:
    inputs:
      workers:
        description: 'Number of parallel workers'
        type: choice
        required: true
        default: '1'
        options:
          - 1
          - 2
          - 4
      environment:
        description: 'Environment'
        type: choice
        required: true
        default: 'local'
        options:
          - local
          - ci
          - prod
      test-name:
        description: 'Test name'
        type: choice
        required: true
        options:
          - './tests/leonardo.spec.ts'
          - 'image-generation.spec.ts'
      browser:
        description: 'Browser'
        type: choice
        required: true
        default: 'chromium'
        options:
          - 'chromium'
          - 'firefox'
          - 'webkit'
jobs:
  run-playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
         working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3 
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: WEB_URL="\${{ vars.WEB_URL }}\" npx playwright test ${{ inputs.test-name }} --project=${{ inputs.browser }} --workers=${{ inputs.workers }}
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: playwright-report
          path: ./playwright-report
          retention-days: 5